name: "GitHub Action for pytest"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  test_package:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
        run: make run_tests